#pragma once

enum class TileType {
	EMPTY,
	WALL_HORIZONTAL_TOP,
	WALL_HORIZONTAL_BOTTOM,
	WALL_VERTICAL_LEFT,
	WALL_VERTICAL_RIGHT,
	WALL_ROUNDED_TOP_LEFT,
	WALL_ROUNDED_TOP_RIGHT,
	WALL_ROUNDED_BOTTOM_LEFT,
	WALL_ROUNDED_BOTTOM_RIGHT
};
